#!/usr/bin/env bash

#check for bucket name 
if [ -z "$1" ]; then
    echo "There need to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
#https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/create-bucket.html
aws s3api create-bucket --bucket $BUCKET_NAME \
--create-bucket-configuration="LocationContstraint=us-west-1"
